spring:
  application:
    name: admin-api
  profiles:
    active: private

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:default}
  observations:
    key-values:
      application: ${spring.application.name}
