spring:
  application:
    name: admin-api
  profiles:
    active: private
  config:
    import: optional:file:../.env[.properties]

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:default}
  observations:
    key-values:
      application: ${spring.application.name}

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${spring.profiles.active:default}
  send-default-pii: true
  traces-sample-rate: 1.0
